# golangci-lint configuration for llm-providers
# See https://golangci-lint.run/usage/configuration/ for full options

run:
  # Timeout for analysis
  timeout: 5m
  
  # Set build tags
  build-tags:
    - integration

# Output configuration
output:
  # Print linter name in issue line
  print-issued-lines: true
  # Print linter name in unused line
  print-linter-name: true
  # Sort results by: severity|filepath|linter
  sort-results: false

# Linters configuration
linters:
  # Use fast preset as base, then customize
  # Fast preset includes: gofmt, goimports, govet, staticcheck, unused, gosimple, structcheck, varcheck, ineffassign, deadcode, typecheck
  fast: true
  
  # Disable specific linters that are too strict or not needed
  disable:
    - gochecknoinits    # Allow init functions
    - gochecknoglobals  # Allow global variables
    - wrapcheck         # Error wrapping - can be noisy
    - exhaustruct       # Optional struct fields
    - forcetypeassert   # Sometimes type assertions are necessary
    - gocognit          # Cognitive complexity (can enable if needed)
    - gocyclo           # Cyclomatic complexity (can enable if needed)
    - godot             # Comment formatting too strict
    - ireturn           # Interface returns (too strict)
    - testpackage       # Allow test files in same package
    - thelper           # Test helper detection (too strict)
    # Style linters - disabled for now to focus on critical issues
    - revive            # Too many style issues - can enable later
    - funlen            # Function length - can relax later
    - dupl              # Duplicate code - less critical
    - goconst           # Magic numbers - low priority
    - whitespace        # Formatting - low priority
    - unconvert         # Unnecessary conversions - low priority
    - unparam           # Unused parameters - low priority
    - gocritic          # Code quality checks - mostly style issues, disabled to reduce noise
  
  # Enable production-critical linters
  enable:
    - gosec             # Security linting - CRITICAL
    - misspell          # Spelling checker - easy fixes
    - errname           # Error naming conventions
    - errorlint         # Error wrapping lint - important
    - unused            # Unused variables, constants, functions, and types
    - errcheck          # Error checking - CRITICAL for production (ensures all errors are handled)
    - govet             # Go vet - catches common bugs (printf check disabled in settings)
    - staticcheck       # Static analysis - finds bugs and suggests improvements
    - gosimple          # Code simplification - prevents bugs through simplification
    - bodyclose         # HTTP response body closing - prevents resource leaks
    - noctx             # Context in HTTP requests - important for cancellation/timeouts

linters-settings:
  # govet settings - disable printf check to allow %w in fmt.Sprintf/log.Fatalf
  # Note: %w is only officially supported in fmt.Errorf, but %v works fine for logging
  govet:
    disable:
      - printf
  
  # goimports settings
  goimports:
    local-prefixes: github.com/manishiitg/multi-llm-provider-go
  
  # gocritic settings
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport      # Can be useful sometimes
      - ifElseChain    # Sometimes clearer
      - captLocal      # Allow local captialization
  
  # gosec security linter
  gosec:
    # Severity level: error, warn, info
    severity: medium
    # Confidence level: low, medium, high
    confidence: medium
    # Note: Lower-priority checks excluded via issues.exclude-rules below
  
  # revive settings
  revive:
    severity: warning
    confidence: 0.8
  
  # staticcheck settings
  staticcheck:
    checks: ["all"]
  
  # misspell settings
  misspell:
    locale: US
  
  # goconst settings
  goconst:
    min-len: 3
    min-occurrences: 3
  
  # funlen settings (function length)
  funlen:
    lines: 100
    statements: 50
  
  # whitespace settings
  whitespace:
    multi-if: false
    multi-func: false
  
  # dupl settings (duplicate code detection)
  dupl:
    threshold: 100

# Issues configuration
issues:
  # Maximum issues count per one linter. Set to 0 to disable.
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0
  
  # Show only new issues created after git revision.
  new: false
  
  # Fix found issues (if it's supported by the linter)
  fix: false
  
  # Make output more machine-readable
  uniq-by-line: true
  
  # Which dirs to skip: they won't be analyzed at all
  exclude-dirs:
    - bin
    - vendor
    - testdata
  
  # Which files to skip
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
  
  # Exclude following linters from requiring explanations
  exclude-rules:
    # Relaxed rules for test files
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - goconst
        - funlen
        - gocognit
    
    # Allow unused parameters in test files
    - path: _test\.go
      text: "parameter.*should have a comment"
      linters:
        - revive
    
    # Allow long lines in test files
    - path: _test\.go
      linters:
        - lll
    
    # Exclude lower-priority gosec checks (focus on critical security issues)
    # Only critical issues remain: G201/G202 (SQL injection), G204 (command injection), G304 (path traversal), G101 (hardcoded credentials)
    # Note: G101 is kept enabled to catch real hardcoded credentials (false positives handled with nolint)
    - linters:
        - gosec
      text: "G104: Errors unhandled"
    - linters:
        - gosec
      text: "G301: Expect directory permissions"
    - linters:
        - gosec
      text: "G306: Expect WriteFile permissions"
    - linters:
        - gosec
      text: "G107: Potential HTTP request"
    - linters:
        - gosec
      text: "G114: Use of net/http serve"
    - linters:
        - gosec
      text: "G115: integer overflow"
    - linters:
        - gosec
      text: "G302: Expect file permissions"

# Severity configuration (optional - commented out for simpler config)
# severity:
#   default-severity: error
#   case-sensitive: false
#   rules:
#     - linters:
#         - gosec
#       severity: error
#     - linters:
#         - misspell
#         - dupl
#       severity: warning

